// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxctjqcqkbnogpqqlbox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Y3RqcWNxa2Jub2dwcXFsYm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mjk3MzIsImV4cCI6MjA3MzMwNTczMn0.DA_fkRFuHo24Zh4BHMbg87dvJACRMZzozQgUdIualk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});